DROP INDEX idx_CzechDAYS_RID;
DROP INDEX idx_days_age_range_day_age_2023;
DROP INDEX idx_CzechDAYS_vd1_age;
DROP INDEX idx_CzechDAYS_vd2_age;
DROP INDEX idx_CzechDAYS_vd3_age;
DROP INDEX idx_CzechDAYS_vd4_age;
DROP INDEX idx_CzechDAYS_vd5_age;
DROP INDEX idx_CzechDAYS_vd6_age;
DROP INDEX idx_CzechDAYS_vd7_age;
DROP INDEX idx_CzechDAYS_d_age;

DROP VIEW PVT_NUM_D;
DROP VIEW PVT_NUM_DUVX;
DROP VIEW PVT_NUM_DVX;
DROP VIEW PVT_NUM_DVD1;
DROP VIEW PVT_NUM_DVD2;
DROP VIEW PVT_NUM_DVD3;
DROP VIEW PVT_NUM_DVD4;
DROP VIEW PVT_NUM_DVD5;
DROP VIEW PVT_NUM_DVD6;
DROP VIEW PVT_NUM_DVD7;
DROP VIEW PVT_NUM_POP;
DROP VIEW PVT_NUM_VX;
DROP VIEW PVT_NUM_VD1;
DROP VIEW PVT_NUM_VD2;
DROP VIEW PVT_NUM_VD3;
DROP VIEW PVT_NUM_VD4;
DROP VIEW PVT_NUM_VD5;
DROP VIEW PVT_NUM_VD6;
DROP VIEW PVT_NUM_VD7;
DROP VIEW PVT_NUM_UVX;


DROP TABLE IF EXISTS DAYS_RANGE;
DROP TABLE IF EXISTS AGE_RANGE;
DROP TABLE IF EXISTS DAYS_AGE_RANGE;
DROP TABLE IF EXISTS CzechDAYS;



COMMIT;
